# Generated by Django 5.0.7 on 2024-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
