# Generated by Django 5.0.7 on 2024-07-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='notified',
        ),
    ]
